# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2af0407ea3696c84ca290405e135d69e27b87e0e1c95e05a97ae1797c3e8a23e730c5fa45ac970babe4cefc5ece13150493f666c226fd14b54f00141c6498285

test:
  secret_key_base: 9f33a63c6cef5647cdf548d154eedb7b59d46f0ee4ba43fb686bb7d9b307c6bf5b2aabd645ed1df5637674ffe5c635e3ef63c76d86993a9854c7b2f156d2c99a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
